spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}

logging:
  level:
    org:
      springframework:
        security: DEBUG

mybatis:
  mapper-locations: "classpath:electionsProcedures.xml"

server:
  servlet:
    context-path: /api
